### ISSUE TITLE
Creating enum using method call from within enum throws UnknownEnumMethod

### ISSUE THREAD

**Issue by hxnk** [spatie/enum#82]
After upgrading to v3, I ran into the following issue (this used to work in v2):

Given this enum:

```php
/**
 * @method static self open()
 * @method static self cancelled()
 * @method static self closed()
 */
class SomeStatus extends Enum
{
    public function isFinal()
    {
        return $this->equals(SomeStatus::cancelled(), SomeStatus::closed());
    }
}
```

When calling:
```php
SomeStatus::open()->isFinal();
```
An exception is thrown: `Spatie\Enum\Exceptions\UnknownEnumMethod` 
with `Method cancelled not found on class SomeStatus`.

**Comment by milesizzo** [comment]
+1, this issue just bit me too.

**Comment by brendt** [comment]
I'll look into it this week.

**Comment by brendt** [comment]
I've released a fix in 3.6.1: https://github.com/spatie/enum/releases/tag/3.6.1

**Comment by Gummibeer** [comment]
@brendt is it me or did you forgot to push your code? The last commit is my _v3.6.0_ one 21days ago.

**Comment by brendt** [comment]
https://github.com/spatie/enum/releases/tag/3.6.2

There we are, sorry for the inconvenience!
